app:
  days: [1, 2, 3, 4, 5]
  poll:
    start:
      hour: 8
      minute: 0
    end:
      hour: 17
      minute: 0
  timer:
    interval: 500
  tracksPerPoll: 5

messenger:
  mount: "pubsub"
  host: "localhost"
  port: 8000

mongodb:
  host: "127.0.0.1"
  port: 27017
  database: "fiveoclocksong"

redis:
  host: "127.0.0.1"
  port: 6379
  database: 0

security:
  workFactor: 10

spotify:
  playlistId: "spotify:user:bentruyman:playlist:0k5gquaSqbsaMqEqnwH3qL"

